name: Send Messages

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  send-messages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run script
        id: run-script
        run: python src/main.py --debug=True
        continue-on-error: true

  redrive:
    runs-on: ubuntu-latest
    needs: send-messages
    if: needs.send-messages.result == 'failure'
    steps:
      - name: Trigger redrive on failure
        uses: peter-evans/repository-dispatch@v3
        with:
          event-type: redrive-messages
          client-payload: '{"num_tries": "1"}'
