name: Send Messages

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
  push:

jobs:
  send-messages:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run script
        id: run-script
        # run: python src/main.py --debug=True
        run: exit 0
        continue-on-error: false

  redrive:
    permissions: write-all
    needs: send-messages
    if: ${{ failure() }}
    runs-on: ubuntu-latest

    steps:
      - name: Redrive workflow
        uses: peter-evans/repository-dispatch@v3
        with:
          event-type: redrive-messages
          client-payload: >-
            {
              "num_tries": "${{ 1 }}"
            }