name: Send Messages

on:
  repository_dispatch:
    types: [redrive-messages]
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
  push:

env:
  MAX_TRIES: 2

jobs:
  send-messages:
    permissions: write-all
    runs-on: ubuntu-latest
    outputs:
      num_try: ${{ steps.set-num-try.outputs.num_try }}
      max_tries: ${{ steps.export-max-tries.outputs.max_tries }}


    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run script
        id: run-script
        env:
          # NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DB_ID_classes: ${{ secrets.NOTION_DB_ID_CLASSES }}
          NOTION_DB_ID_instructors: ${{ secrets.NOTION_DB_ID_INSTRUCTORS }}
          NOTION_DB_ID_students: ${{ secrets.NOTION_DB_ID_STUDENTS }}
          WHATSAPP_API_TOKEN: ${{ secrets.WHATSAPP_API_TOKEN }}
        run: python src/main.py --debug=True
      
      - name: Prepare Retry Count
        if: ${{ failure() && steps.run-script.outcome != 'success' }}
        id: set-num-try
        run: |
          NUM_TRY=$(( ${{ github.event.client_payload.num_tries || 0 }} + 1 ))
          echo "NUM_TRY=$NUM_TRY"
          echo "num_try=$NUM_TRY" >> "$GITHUB_OUTPUT"

      - name: Export max tries
        if: always()
        id: export-max-tries
        run: |
          echo "max_tries=$MAX_TRIES" >> "$GITHUB_OUTPUT"
        

  redrive:
    permissions: write-all
    needs: send-messages
    if: ${{ failure() && needs.send-messages.outputs.num_try < needs.send-messages.outputs.max_tries }}
    runs-on: ubuntu-latest

    steps:
      - name: Redrive workflow
        uses: peter-evans/repository-dispatch@v3
        with:
          event-type: redrive-messages
          client-payload: >-
            {
              "num_tries": "${{ needs.send-messages.outputs.num_try }}"
            }

  notify-failure:
    permissions: write-all
    needs: send-messages
    if: ${{ failure() && needs.send-messages.outputs.num_try == needs.send-messages.outputs.max_tries }}
    runs-on: ubuntu-latest

    steps:
      - name: Notify on final failure
        run: echo "Final attempt failed. Send notification here."