name: Job Status Example

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Building..."
  
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo "Running tests..."
      - run: exit 1  # simulate test failure

  notify-success:
    runs-on: ubuntu-latest
    needs: test
    if: ${{ success() }}
    steps:
      - run: echo "✅ Tests passed!"

  notify-failure:
    runs-on: ubuntu-latest
    needs: test
    if: ${{ failure() }}
    steps:
      - run: echo "❌ Tests failed!"
